// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	// v1 "k8s.io/kube-scheduler/config/v1"
)


// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LowRiskOverCommitmentArgs) DeepCopyInto(out *LowRiskOverCommitmentArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.TrimaranSpec = in.TrimaranSpec
	if in.RiskLimitWeights != nil {
		in, out := &in.RiskLimitWeights, &out.RiskLimitWeights
		*out = make(map[corev1.ResourceName]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LowRiskOverCommitmentArgs.
func (in *LowRiskOverCommitmentArgs) DeepCopy() *LowRiskOverCommitmentArgs {
	if in == nil {
		return nil
	}
	out := new(LowRiskOverCommitmentArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LowRiskOverCommitmentArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricProviderSpec) DeepCopyInto(out *MetricProviderSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricProviderSpec.
func (in *MetricProviderSpec) DeepCopy() *MetricProviderSpec {
	if in == nil {
		return nil
	}
	out := new(MetricProviderSpec)
	in.DeepCopyInto(out)
	return out
}
// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrimaranSpec) DeepCopyInto(out *TrimaranSpec) {
	*out = *in
	out.MetricProvider = in.MetricProvider
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrimaranSpec.
func (in *TrimaranSpec) DeepCopy() *TrimaranSpec {
	if in == nil {
		return nil
	}
	out := new(TrimaranSpec)
	in.DeepCopyInto(out)
	return out
}
